# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|

  config.vm.define :mysql01 do |mysql01| 
    mysql01.vm.box = "precise64"
    mysql01.vm.box_url = "http://files.vagrantup.com/precise64.box"

    mysql01.vm.network :hostonly, "12.0.0.23"    
    mysql01.vm.host_name = "mysql01"
    mysql01.vm.provision :puppet do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "mysql.pp"
    end
  end
  
end
