# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|

  config.vm.define :postgresql01 do |namenode| 
    namenode.vm.box = "precise64"
    namenode.vm.box_url = "http://files.vagrantup.com/precise64.box"

    namenode.vm.network :hostonly, "12.0.0.23"    
    namenode.vm.host_name = "postgresql01"
    namenode.vm.provision :puppet do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "postgresql.pp"
    end
  end
  
end
