# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.define :postgresql01 do |postgresql01| 
    postgresql01.vm.box = "precise64"
    postgresql01.vm.box_url = "http://files.vagrantup.com/precise64.box"

    postgresql01.vm.network :hostonly, "12.0.0.23"    
    postgresql01.vm.host_name = "postgresql01"
    postgresql01.vm.provision :puppet do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "postgresql.pp"
    end
  end
  
end
